### ISSUE TITLE
Compatibility issue with transformers >= 4.0.0

### ISSUE THREAD

**Issue by bjascob** [bjascob/amrlib#9]
See #8 for behavior when running the stog model with transformers 4.0.0

The requirements.txt for amrlib v0.2.1 did not require transformers==3.5.1, but I added the version to that file.  Code works with transformers==3.4.0 too, so it's probably OK to just do transformers<=3.5.1.

Review transformers 4 and consider changing code to support this version.  Note that while the original error was reported for the stog model, the gtos model could have issues too.

**Comment by bjascob** [comment]
Fixed issues with inference in parse and generate models.
Training parse appears to work correctly (with torch 1.6.0, not 1.7.0), though I only tested that this works for 1 epoch.
Training the generate model now produces the following message...
  File "./10_Train.py", line 17, in <module>
  File "/home/bjascob/Files/Projects/AMR/012_AMRLib_GitHub/amrlib/models/generate_t5/trainer.py", line 59, in __init__
    self.training_args = TrainingArguments(**args['hf_args'])
TypeError: __init__() got an unexpected keyword argument 'evaluate_during_training'

**Comment by bjascob** [comment]
Fixed by removing `evaluate_during_training` from config and changing `lm_labels` to `labels` in generate trainer.

**Comment by bjascob** [comment]
Complete with release of amrlib 0.2.2
